import Head from "next/head";
import Image from "next/image";
import { Bubblegum_Sans, Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "../components/bubbles"
import Bubbles from "../components/bubbles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const wordSource = [
  "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
  "kiwi", "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry",
  "strawberry", "tangerine", "ugli", "vanilla", "watermelon", "xigua", "yam", "zucchini",
  "apricot", "blackberry", "blueberry", "cantaloupe", "coconut", "cranberry", "currant",
  "dragonfruit", "gooseberry", "grapefruit", "guava", "jackfruit", "kumquat", "lime",
  "lychee", "mandarin", "mulberry", "olive", "passionfruit", "peach", "pear", "persimmon",
  "pineapple", "plum", "pomegranate", "starfruit", "tamarind",
  "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
  "kiwi", "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry",
  "strawberry", "tangerine", "ugli", "vanilla", "watermelon", "xigua", "yam", "zucchini",
  "apricot", "blackberry", "blueberry", "cantaloupe", "coconut", "cranberry", "currant",
  "dragonfruit", "gooseberry", "grapefruit", "guava", "jackfruit", "kumquat", "lime",
  "lychee", "mandarin", "mulberry", "olive", "passionfruit", "peach", "pear", "persimmon",
  "pineapple", "plum", "pomegranate", "starfruit", "tamarind"
];

// Function to generate a list of random dictionary words
const generateRandomDictionaryWords = (numWords: number) => {
  const words = [];
  for (let i = 0; i < numWords; i++) {
    const index = i % wordSource.length;
    words.push(wordSource[index]);
  }
  return words;
};

const randomWords = generateRandomDictionaryWords(200); // Generate 100 random dictionary words

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
            <Bubbles content={randomWords}/>
            </main>
      </div>
    </>
  );
}
